desc "Create countries with corresponding regions"
  task :create_countries => :environment do 
  Country.create(region_id: 2, name: "Ireland")
  Country.create(region_id: 1, name: "United Kingdom")
  Country.create(region_id: 3, name: "Austria")
  Country.create(region_id: 3, name: "Belgium")
  Country.create(region_id: 3, name: "Bulgaria")
  Country.create(region_id: 3, name: "Croatia")
  Country.create(region_id: 3, name: "Cyprus")
  Country.create(region_id: 3, name: "Czech Republic")
  Country.create(region_id: 3, name: "Denmark")
  Country.create(region_id: 3, name: "Estonia")
  Country.create(region_id: 3, name: "Finland")
  Country.create(region_id: 3, name: "France")
  Country.create(region_id: 3, name: "Germany")
  Country.create(region_id: 3, name: "Greece")
  Country.create(region_id: 3, name: "Hungary")
  Country.create(region_id: 3, name: "Italy")
  Country.create(region_id: 3, name: "Latvia")
  Country.create(region_id: 3, name: "Lithuania")
  Country.create(region_id: 3, name: "Luxembourg")
  Country.create(region_id: 3, name: "Malta")
  Country.create(region_id: 3, name: "Netherlands")
  Country.create(region_id: 3, name: "Poland")
  Country.create(region_id: 3, name: "Portugal")
  Country.create(region_id: 3, name: "Romania")
  Country.create(region_id: 3, name: "Slovakia")
  Country.create(region_id: 3, name: "Slovenia")
  Country.create(region_id: 3, name: "Spain")
  Country.create(region_id: 3, name: "Sweden")
  Country.create(region_id: 3, name: "European Union")
end